name: Publish to PyPI

on:
  release:
    types: [prereleased, released]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.41.4
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - name: Install Hatch
        run: pip install hatch
      - name: Build package
        run: hatch build
      # Publish to Test PyPI (only for pre-releases)
      - name: Publish to Test PyPI
        if: github.event.release.prerelease == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      # Publish to PyPI (only for releases)
      - name: Publish to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1
