name: Test

on:
  release:
    types: [prereleased, released]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Pre-release
        if: github.event.release.prerelease == true
        run: echo "RAN PRE-RELEASE"
      - name: Release
        if: github.event.release.prerelease == false
        run: echo "RAN RELEASE"
